version: 0.1.{build}-{branch}
image:
- Visual Studio 2017
- Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: detailed
test_script:
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:" -noshadow" -output:"coverage.xml" -filter:"+[openTSDB.net*]* -[openTSDB.net.Tests*]*"
after_test:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
deploy:
- provider: NuGet
  api_key:
    secure: bC27CLQTwagax6ZX6EFu33b1NtlE7yx6Qif/GgAxcSYInH4PBrB6uIltlNVvEjvw
  on:
    branch: master