version: 0.1.{build}-{branch}
image:
- Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: openTSDB.net.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: detailed
test:
  categories:
    except:
    - Integration
after_test:
- .\packages\OpenCover.4.6.247-rc\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"C:\projects\opentsdb-net\openTSDB.net\openTSDB.net.Tests\bin\Debug\openTsdb.net.Tests.dll -noshadow -appveyor" -returntargetcode -filter:"+[openTsdb*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -excludebyfile:*\*Designer.cs -hideskipped:All -output:.\coverage.xml
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "coverage.xml"
deploy:
- provider: NuGet
  api_key:
    secure: bC27CLQTwagax6ZX6EFu33b1NtlE7yx6Qif/GgAxcSYInH4PBrB6uIltlNVvEjvw
  on:
    branch: master