version: 2.0.{build}
image:
  - Visual Studio 2017
  - Ubuntu1804
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
  - cmd: dotnet build
test_script:
  - cmd: >-
      dotnet test openTSDB.net.Test/openTSDB.net.Test.csproj


      dotnet pack ./openTSDB.net/openTSDB.net.csproj --configuration Release --output nupkgs
artifacts:
  - path: openTSDB.net/nupkgs/*
    name: nuGet